#!/usr/bin/env python3
"""
Convert splash image header files to binary data files for SPIFFS storage.
This reduces firmware size by moving large image data from flash to SPIFFS.
"""
import os
import re

def extract_array_from_header(header_file_path):
    """Extract binary data from C header file array definition."""
    with open(header_file_path, 'r') as f:
        content = f.read()
    
    # Find the array name and data
    array_match = re.search(r'const\s+unsigned\s+char\s+(\w+)\s*\[\]\s*PROGMEM\s*=\s*\{([^}]+)\};', content, re.DOTALL)
    if not array_match:
        # Try uint16_t format 
        array_match = re.search(r'const\s+uint16_t\s+(\w+)\s*\[\]\s*PROGMEM\s*=\s*\{([^}]+)\};', content, re.DOTALL)
        if not array_match:
            print(f"Could not find array in {header_file_path}")
            return None, None, None
        data_type = 'uint16_t'
    else:
        data_type = 'uint8_t'
    
    array_name = array_match.group(1)
    array_data = array_match.group(2)
    
    # Extract hex values
    hex_values = re.findall(r'0x[0-9a-fA-F]+', array_data)
    
    if data_type == 'uint16_t':
        # Convert to bytes (little endian for ESP32)
        byte_data = bytearray()
        for hex_val in hex_values:
            val = int(hex_val, 16)
            byte_data.append(val & 0xFF)         # Low byte
            byte_data.append((val >> 8) & 0xFF)  # High byte
    else:
        # Convert to bytes
        byte_data = bytearray(int(hex_val, 16) for hex_val in hex_values)
    
    return array_name, byte_data, data_type

def main():
    """Convert all splash image headers to binary files."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    splash_dir = os.path.join(project_dir, 'src', 'splash_image')
    data_dir = os.path.join(project_dir, 'data')
    
    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)
    
    # Process each header file
    header_files = [
        'biies.h', 'hedon.h', 'mazduino.h', 
        'mercy.h', 'spine.h', 'zycas.h'
    ]
    
    converted_files = []
    total_size = 0
    
    for header_file in header_files:
        header_path = os.path.join(splash_dir, header_file)
        
        if not os.path.exists(header_path):
            print(f"Warning: {header_path} not found")
            continue
            
        print(f"Converting {header_file}...")
        
        array_name, byte_data, data_type = extract_array_from_header(header_path)
        
        if byte_data is None:
            print(f"Failed to extract data from {header_file}")
            continue
            
        # Create binary file
        binary_filename = header_file.replace('.h', '.bin')
        binary_path = os.path.join(data_dir, binary_filename)
        
        with open(binary_path, 'wb') as f:
            f.write(byte_data)
        
        file_size = len(byte_data)
        total_size += file_size
        
        print(f"  -> {binary_filename} ({file_size:,} bytes, {data_type})")
        converted_files.append((binary_filename, array_name, data_type))
    
    print(f"\nConversion complete!")
    print(f"Total binary data: {total_size:,} bytes ({total_size/1024/1024:.1f} MB)")
    print(f"Files created in: {data_dir}")
    
    # Create info file for the C++ code
    info_content = "// Auto-generated image file info\n"
    info_content += "// Generated by convert_images.py\n\n"
    
    for filename, array_name, data_type in converted_files:
        info_content += f"// {filename}: {array_name} ({data_type})\n"
    
    info_path = os.path.join(data_dir, 'image_info.txt')
    with open(info_path, 'w') as f:
        f.write(info_content)
    
    print(f"\nImage info written to: image_info.txt")
    print("\nNext steps:")
    print("1. Upload SPIFFS data: pio run --target uploadfs")
    print("2. Modify SplashScreen.cpp to load from SPIFFS")
    print("3. Remove splash_image header includes")

if __name__ == '__main__':
    main()