#!/usr/bin/env python3

import os
import time
import hashlib
import subprocess
from datetime import datetime

def get_git_info():
    """Get git commit hash and branch info if available"""
    try:
        # Get current commit hash
        commit_hash = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'], 
                                            stderr=subprocess.DEVNULL).decode().strip()
        
        # Get current branch
        branch = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], 
                                       stderr=subprocess.DEVNULL).decode().strip()
        
        # Check if working directory is clean
        status = subprocess.check_output(['git', 'status', '--porcelain'], 
                                       stderr=subprocess.DEVNULL).decode().strip()
        dirty = '+' if status else ''
        
        return commit_hash + dirty, branch
    except:
        return "unknown", "unknown"

def get_build_number():
    """Generate or increment build number"""
    build_file = "build_number.txt"
    build_number = 1
    
    if os.path.exists(build_file):
        try:
            with open(build_file, 'r') as f:
                build_number = int(f.read().strip()) + 1
        except:
            build_number = 1
    
    with open(build_file, 'w') as f:
        f.write(str(build_number))
    
    return build_number

def generate_version_header():
    """Generate version header file"""
    
    # Get build info
    build_number = get_build_number()
    commit_hash, branch = get_git_info()
    build_time = datetime.now()
    
    # Format version string
    version_major = 1
    version_minor = 3
    version_patch = build_number
    
    version_string = f"{version_major}.{version_minor}.{version_patch}"
    build_date = build_time.strftime("%Y-%m-%d")
    build_time_str = build_time.strftime("%H:%M:%S")
    build_timestamp = int(time.time())
    
    # Generate header content
    header_content = f'''#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// DO NOT EDIT THIS FILE MANUALLY

#define VERSION_MAJOR {version_major}
#define VERSION_MINOR {version_minor}
#define VERSION_PATCH {version_patch}
#define VERSION_BUILD {build_number}

#define VERSION_STRING "{version_string}"
#define BUILD_DATE "{build_date}"
#define BUILD_TIME "{build_time_str}"
#define BUILD_TIMESTAMP {build_timestamp}
#define BUILD_HASH "{commit_hash}"
#define BUILD_BRANCH "{branch}"

// Full version info
#define FULL_VERSION_STRING "v{version_string} ({commit_hash})"
#define BUILD_INFO "Built on {build_date} {build_time_str}"

#endif // VERSION_H
'''
    
    # Write header file
    include_dir = "include"
    if not os.path.exists(include_dir):
        os.makedirs(include_dir)
    
    header_path = os.path.join(include_dir, "version.h")
    with open(header_path, 'w') as f:
        f.write(header_content)
    
    print(f"Generated version: {version_string} (build {build_number})")
    print(f"Git: {commit_hash} on {branch}")
    print(f"Built: {build_date} {build_time_str}")

if __name__ == "__main__":
    generate_version_header()