#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// DO NOT EDIT THIS FILE MANUALLY

#define VERSION_MAJOR 1
#define VERSION_MINOR 3
#define VERSION_PATCH 4
#define VERSION_BUILD 4

#define VERSION_STRING "1.3.4"
#define BUILD_DATE "2026-01-01"
#define BUILD_TIME "21:53:53"
#define BUILD_TIMESTAMP 1767279233
#define BUILD_HASH "2cd510a+"
#define BUILD_BRANCH "main"

// Full version info
#define FULL_VERSION_STRING "v1.3.4 (2cd510a+)"
#define BUILD_INFO "Built on 2026-01-01 21:53:53"

#endif // VERSION_H
