#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// DO NOT EDIT THIS FILE MANUALLY

#define VERSION_MAJOR 1
#define VERSION_MINOR 3
#define VERSION_PATCH 6
#define VERSION_BUILD 6

#define VERSION_STRING "1.3.6"
#define BUILD_DATE "2026-03-06"
#define BUILD_TIME "18:39:31"
#define BUILD_TIMESTAMP 1772797171
#define BUILD_HASH "abe647e+"
#define BUILD_BRANCH "dev_KMRTM35018-SPI"

// Full version info
#define FULL_VERSION_STRING "v1.3.6 (abe647e+)"
#define BUILD_INFO "Built on 2026-03-06 18:39:31"

#endif // VERSION_H
